export const allEvents = [
    {
      id: '1',
      title: 'Concert électro',
      date: '2025-04-22',
      time: '20:00',
      location: 'Paris - Bataclan',
      description: 'Une soirée électro avec les meilleurs DJ du moment.',
    },
    {
      id: '2',
      title: 'Festival de jazz',
      date: '2025-05-01',
      time: '18:00',
      location: 'Marseille - Vieux Port',
      description: '3 jours de concerts jazz en plein air.',
    },
    {
      id: '3',
      title: 'Soirée étudiante',
      date: '2025-04-25',
      time: '22:00',
      location: 'Lyon - Le Sucre',
      description: 'Viens fêter la fin des partiels avec nous !',
    },
    {
      id: '4',
      title: 'Anniversaire de Lola',
      date: '2025-05-10',
      time: '19:30',
      location: 'Toulouse - Chez Lola',
      description: 'Viens fêter les 25 ans de Lola ',
    },
    {
      id: '5',
      title: 'Marathon de Bordeaux',
      date: '2025-06-02',
      time: '08:00',
      location: 'Bordeaux - Quais',
      description: '42km à travers les rues de Bordeaux.',
    },
    {
      id: '6',
      title: 'Apéro rooftop',
      date: '2025-04-30',
      time: '18:30',
      location: 'Nice - Roof by the Sea',
      description: 'DJ, cocktails et sunset ',
    },
    {
      id: '7',
      title: 'Projection film en plein air',
      date: '2025-07-15',
      time: '21:30',
      location: 'Nantes - Parc du Grand Blottereau',
      description: 'Ciné sous les étoiles avec popcorn offert !',
    },
    {
      id: '8',
      title: 'Tournoi de basket 3v3',
      date: '2025-05-20',
      time: '10:00',
      location: 'Lille - Gymnase Municipal',
      description: 'Forme ton équipe et viens gagner la coupe ',
    },
    {
      id: '9',
      title: 'Fête de la musique',
      date: '2025-06-21',
      time: 'Toute la journée',
      location: 'Dans toute la France',
      description: 'Musique gratuite dans toutes les rues !',
    },
    {
      id: '10',
      title: 'Atelier de cuisine',
      date: '2025-05-05',
      time: '15:00',
      location: 'Montpellier - La Fabrique',
      description: 'Découvre les bases de la cuisine thaïlandaise ',
    },
  ];
  